apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-x3el
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-x3el@sha256:5dc665cb659e5ccdbf1a4e42dbca50ac17400e1d5010d2891537adb20d63fc12
        name: my-nodejs
        resources: {}
status: {}
